const namesNumbers = [
  "L'uuuuuuuuh quexungu",
  "L'ànec",
  "El trio",
  "La cadira",
  "El duro",
  "Mitja dotzena",
  "En Compi 7 titits",
  "Una mamella",
  "Toca't un ou",
  "La puta d'oros",
  "La diada",
  "Les campanades",
  "El de la mala sort",
  "Agafa un cagarro i... esmorza!",
  "La niña bonita",
  "Mengen fetge d'un penjat...",
  "Deu amb set",
  "Ja us podeu treure el carnet",
  "Sant Josep",
  "El pelat vint",
  "Vint-i-uuuuun litres i mig de Letona, llet de la bona",
  "La parelleta d'ànecs",
  "Sant Jordi",
  "Sant Joan",
  "Fum, fum, fum!",
  "Sant Esteve",
  "La mare de Déu de Montserrat",
  "Els sants innocents",
  "El tramvia",
  "Trientra bé",
  "Per la porta o per la finestra... Sant Silvestre",
  "En trempen dos: l'amo i el gos",
  "Les Teresines",
  "Te n'entren quatre",
  "Ja en trempen la meitat",
  "Tres dotzenes",
  "Al mig de la guerra",
  "En trempen molts mirant la mamella",
  "L'any que es va acabar la guerra",
  "L'Alí Babà i els 40 lladres",
  "Culample petit",
  "-",
  "El licor",
  "Dues cadires",
  "Tres quarts d'hora",
  "Il Dottore, Valentino Rossi",
  "-",
  "Culample mamellut",
  "Culample nou",
  "La teva mare canta",
  "S'hi encanta un",
  "Se n'hi encanten dos: l'amo i el gos",
  "Se n'hi encanten tres",
  "Se n'hi encanten quatre",
  "Parella de músics",
  "L'any de la fred",
  "Se n'hi encanten set",
  "Se n'hi encanten buit",
  "S'hi encanten tots",
  "El prejubilat",
  "-",
  "Barça, 6 - Madrid, 2",
  "L'any de la millor collita",
  "Quasi jubilat",
  "La jubilació",
  "Parella de sisos",
  "-",
  "Gairebé el més verro, jo te xumo i tu me la deus",
  "El més verro",
  "Pelat la tieta",
  "-",
  "-",
  "-",
  "L'edat de viatjar amb l'Imserso",
  "Tres ralets",
  "-",
  "Les banderes d'Itàlia",
  "L'edat del pavo",
  "-",
  "La iaia",
  "-",
  "El Naranjito",
  "-",
  "-",
  "-",
  "-",
  "-",
  "Les mamelles de la Paula",
  "-",
  "L'avi, pelut, geperut",  
];

export default namesNumbers;
